config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "users#index"
  resources :users, only: [:edit, :update]
  resources :lines, only: [:edit, :update] do
    resources :stations, only: [:index] do
      resources :messages, only: [:index,:create]
      namespace :api do
        resources :messages, only: :index, defaults: { format: 'json' }
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line.rb
class Line < ApplicationRecord
  has_many :line_users
  has_many :users, through: :line_users
  has_many :line_stations
  has_many :stations, through: :line_stations
  has_many :messages
  validates :name, presence: true, uniqueness: true
end

app/models/line_station.rb
class LineStation < ApplicationRecord
  belongs_to :line
  belongs_to :station
end

app/models/line_user.rb
class LineUser < ApplicationRecord
  belongs_to :line
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :line
  belongs_to :station
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :line_stations
  has_many :lines, through: :line_stations
  has_many :messages
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :line_users
  has_many :lines, through: :line_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages =Message.where(line_id:params[:line_id],station_id:params[:station_id]).includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def edit
    
  end

  def update
    if current_user.update(lines_params)
      redirect_to root_path, notice: '登録路線を更新しました'
    else
      render :edit
    end
  end

  private
  def lines_params
    params.require(:user).permit(:name, line_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_line,:set_station

  def index 
    @message = Message.new
    @messages =Message.where(line_id:params[:line_id],station_id:params[:station_id])
  end

  def create
    @message = Message.new(message_params)
    @message.line_id=@line.id
    @message.station_id=@station.id
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @station.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end
  
  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_line
    @line = Line.find(params[:line_id])
  end

  def set_station
    @station = Station.find(params[:station_id])
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_line
  
  def index
    
  end

  private
  def set_line
    @line = Line.find(params[:line_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TrainChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/lines/edit.html.haml
= form_for current_user,:url => { :controller => :lines, :action => :update } do |f|  
  = f.collection_check_boxes :line_ids, Line.all, :id, :name
  = f.submit "Save", class: "chat-line-form__action-btn"

app/views/messages/_message.html.haml
.chat__message-list__message{data: {message: {id: message.id}}}
  .chat__message-list__message__inline
    .chat__message-list__message__inline__upper
      .chat__message-list__message__inline__upper__user-name
        = message.user.name
      .chat__message-list__message__inline__upper__date
        = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .chat__message-list__message__inline__lower
      - if message.content.present?
        %p.chat__message-list__message__inline__lower__content
          = message.content
      = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render "parts/train"
  = render "parts/side"
  = render "parts/chat"

app/views/parts/_chat.html.haml
.chat
  .chat__message-list
    -if @line!=nil && @station!=nil
      = render @messages
    -else
      .no-select
        ③駅を選択してください
  .chat__form 
    -if @line!=nil && @station!=nil 
      = form_for [@line,@station,@message] do |f|
        .input-box
          = f.text_field :content, class: 'input-box__text', placeholder: '駅の情報を共有しましょう！'
          = f.label :image, class: 'input-box__image' do
            = icon('fas', 'image', class: 'icon')
            = f.file_field :image, class: 'input-box__image__file'
        = f.submit 'Send', class: 'submit-btn'
    -else
      .no-select
        ③駅を選択してください

app/views/parts/_side.html.haml
.side
  .side__user
    .side__user__name
      = current_user.name
    .side__user__register_line
      = link_to "路線登録",edit_line_path(current_user)
    .side__user__logout
      = link_to "ログアウト",edit_user_path(current_user) 
  .side__line-list
    -if !current_user.lines.empty?
      - current_user.lines.each do |line|
        = link_to line_stations_path(line), class: "line" do
          = image_tag src=line.image, alt: '写真', height: '30'
          = line.name+'線'
    -else
      .no-select
        ①路線を登録してください

app/views/parts/_train.html.haml
.train
  .train__line-image
    -if @line!=nil
      = image_tag src=@line.image, alt: '写真', height: '50'
    -else
      .no-select
        ②路線を選択してください
  .train__line-name
    -if @line!=nil
      = @line.name+'線'
    -else
      .no-select
        ②路線を選択してください
  .train__station
    -if @line!=nil
      - @line.stations.each do |station|
        = link_to line_station_messages_path(@line,station), class: "station" do    
          = station.name
    -else
      .no-select
        ②路線を選択してください
  .train__station-detail
    -if @line!=nil && @station!=nil
      .station-info
        =@station.name+'駅'
      .line-info
        - @station.lines.each do |line|
          -if @line != line
            = link_to line_station_messages_path(line,@station) do
              = line.name
    -else
      .no-select
        ③駅を選択してください

app/views/stations/index.html.haml
.wrapper
  = render "parts/train"
  = render "parts/side"
  = render "parts/chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
.wrapper
  = render "parts/train"
  = render "parts/side"
  = render "parts/chat"